### PR TITLE
Upgrade pact packages to work with M1 mac

### PR DESCRIPTION
**Pull request by michelle-vel**
In order to get this to work on my M1 mac, I had to upgrade the pact version

### CODE REVIEW

**Review by rymaju — APPROVED** [review]
LGTM

**Review by rymaju — CHANGES_REQUESTED** [review]
Actually wait the lock file looks suspicious 🤔

**Review by onb6 — APPROVED** [review]
Woot!!🥳

**Comment by onb6** [comment]
> Actually wait the lock file looks suspicious 🤔

Why does it still tagged as an xl PR? Do you think it actually required that many updates?

**Review by rymaju — APPROVED** [review]
LGTM

**Comment by rymaju** [comment]
> > Actually wait the lock file looks suspicious 🤔
> 
> Why does it still tagged as an xl PR? Do you think it actually required that many updates?

Just what happens when you change the lockfile, the actual change is 2 lines but we do need to make sure the lockfile is up to date and in github

**Pull request merged**
